print("*--------------------*")
print("Primer programa para saludar en python")
print("*--------------------*")
print("Hola Mundo / Hello World")
print("*--------------------*")
print("Números del 1 al 5")
print(1)
print(2)
print(3)
print(4)
print(5)